version: '2'
volumes:
        unifi-data:
        uisp-data:
        nginx-data:
        letsencrypt:
services:
        ddclient:
                build: ./ddclient-cloudflare
                privileged: true
        nginx:
                build: ./nginx
                privileged: true
                ports:
                        - "443:443"
                volumes:
                        - "nginx-data:/app/data"
                        - "letsencrypt:/etc/letsencrypt"

                links:
                        - "unifi"
                        - "uisp"
        unifi:
                build: ./unifi
                ports:
                        # See https://help.ubnt.com/hc/en-us/articles/218506997-UniFi-Ports-Used
                        - "10001:10001/udp" # AP discovery
                        - "3478:3478/udp" # STUN
                        - "6789:6789" # Mobile speed tests
                        - "8080:8080" # Device controller communication
                volumes:
                        - "unifi-data:/unifi"
        uisp:
                build: ./uisp
                volumes:
                        - "uisp-data:/config"
